"""initial

Revision ID: 0ca39674045a
Revises:
Create Date: 2026-07-01 19:16:15.017422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ca39674045a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('price', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.Column('is_available', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_dishes_name_lowercase', 'dishes', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('is_available IS TRUE'))
    op.create_table('ingredients',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.Column('is_available', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_ingredients_name_lowercase', 'ingredients', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('is_available IS TRUE'))
    op.create_table('outbox_events',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('event_type', sa.SmallInteger(), nullable=False),
            sa.Column('status', sa.SmallInteger(), nullable=False),
            sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_events_pending', 'outbox_events', ['status'], unique=False, postgresql_where=sa.text('status = 1'))
    op.create_table('users',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('email_verification_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('email', sa.String(length=254), nullable=False),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_user_active', 'users', ['email'], unique=True, postgresql_where=sa.text('is_deleted IS FALSE'))
    op.create_table('dish_ingredients',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('dish_id', sa.Uuid(), nullable=False),
            sa.Column('ingredient_id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('dish_id', 'ingredient_id', name='uq_dish_ingredient')
    )
    op.create_index('idx_dish_ingredient', 'dish_ingredients', ['ingredient_id'], unique=False)
    op.create_table('orders',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('total_price', sa.BIGINT(), nullable=False),
            sa.Column('status', sa.SmallInteger(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_user_active', 'orders', ['user_id'], unique=False, postgresql_where=sa.text('status IN (1, 2, 3)'))
    op.create_table('wallets',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('balance', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
            sa.Column('cashback_balance', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
            sa.Column('is_frozen', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id')
    )
    op.execute("ALTER TABLE wallets SET (fillfactor = 76);")
    op.create_table('warehouse',
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('ingredient_id', sa.Uuid(), nullable=False),
            sa.Column('quantity', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
            sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.execute("ALTER TABLE warehouse SET (fillfactor = 67);")
    op.create_table('order_items',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('order_id', sa.Uuid(), nullable=False),
            sa.Column('dish_id', sa.Uuid(), nullable=False),
            sa.Column('quantity', sa.Integer(), nullable=False),
            sa.Column('price_per_unit', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='RESTRICT'),
            sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('warehouse')
    op.drop_table('wallets')
    op.drop_index('idx_orders_user_active', table_name='orders', postgresql_where=sa.text('status IN (1, 2, 3)'))
    op.drop_table('orders')
    op.drop_index('idx_dish_ingredient', table_name='dish_ingredients')
    op.drop_table('dish_ingredients')
    op.drop_index('uq_users_user_active', table_name='users', postgresql_where=sa.text('is_deleted IS FALSE'))
    op.drop_table('users')
    op.drop_index('idx_outbox_events_pending', table_name='outbox_events', postgresql_where=sa.text('status = 1'))
    op.drop_table('outbox_events')
    op.drop_index('uq_ingredients_name_lowercase', table_name='ingredients', postgresql_where=sa.text('is_available IS TRUE'))
    op.drop_table('ingredients')
    op.drop_index('uq_dishes_name_lowercase', table_name='dishes', postgresql_where=sa.text('is_available IS TRUE'))
    op.drop_table('dishes')
    # ### end Alembic commands ###
